language: java

addons:
  sonarcloud:
    organization: "github-mattbertolini"
    token:
      secure: "VHPjg8L6FqHwz2HlW37yDAUxRu5QvzjUcl8lMr7wPJvHi/wq7B2EetshOaszN68wxzkED4CjvRLT2JLwkn59F8SjnAQ0QwUD1C9L/kUX3cASZRGI2Ww5DHBzutaYhNjrofLRDhbdS2Kgnz3pDk24++/FiGqbjlXgOem95bqz8vQEEOkEzjkW5PzzZqBL51IhYlsvb+MqL9qRnApIdgk7IZN5bHTmOCpCi5EdqDy72onn6VCjdMUKqHAcA3zhOPeSr/FL+v8S+y3ytItFTt+0TOKuXlq5T8f0No9Wkr87KU4uxNqeqCk3ymPaPayJATv7c7uW7Va/ALGO6daSZejWAFhinj+UhpuWhdK3VsbQnEftSuXrkxwu1Wj5OTBgjdIjyUw9WxnyLPUOragjdk4WRFnR0g7JGTJoVTsv0x7bylULi16o/s1vxzwCQyOthn8mhynzgOb0kNMZRIh6/vieJTsy36clO+sPw/wB1zMKsQc2wkvLBRiZqbGBNgvWNZtfXuj3ETEWXO3rZnp/Xq8xEJGSck/YTlU1wlcxjnGIzFObMhJh52PdgT42FMguKQiaXsLpZeWfO9AG1cUx77fx7cT0mkCqbhMJ7dMkbmSEvzM8sBbI5YQBi5UbLv6tzSajbwyLkBlnXoc03gxlBn7mM5A15CLyR8urhk9t993Z3X8="

jobs:
  include:
    - name: OpenJDK 17
      jdk: openjdk17
      script: ./gradlew jacocoTestReport sonarqube
