name: build
run-name: CI build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - $default-branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk-version: [17, 21]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This is needed for Sonar to do analysis
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew -Dorg.gradle.welcome=never build jacocoTestReport testCodeCoverageReport sonar
